apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-role-binding
  namespace: esales-staging
subjects:
  - kind: User
    name: parasharprasoon.950@gmail.com
    namespace: esales-staging
roleRef:
  kind: Role
  name: jenkins-role
  apiGroup: rbac.authorization.k8s.io