apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: esales-staging
  name: jenkins-role
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/exec"]
    verbs: ["get", "list", "create", "update", "delete"]