apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: esales-staging
  name: spark-role
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "pods/exec", "configmaps", "services", "persistentvolumeclaims", "endpoints"]
    verbs: ["get", "watch", "list", "create", "delete", "deletecollection"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "create", "delete"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "create", "delete"]