apiVersion: v1
kind: Service
metadata:
  name: my-spark-job2
  namespace: esales-staging
  labels:
    app: my-spark-job1
spec:
  clusterIP: None  # Headless service
  selector:
    app: my-spark-job2
  ports:
    - protocol: TCP
      port: 7078
      targetPort: 7078