apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: esales-staging
  name: kubernetes-api-access
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps", "endpoints", "secrets", "persistentvolumeclaims"]
    verbs: ["*"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "delete"]