apiVersion: v1
kind: Service
metadata:
  name: my-spark-job
  namespace: esales-staging
  labels:
    app: my-spark-job
spec:
  clusterIP: None  # Headless service
  selector:
    app: my-spark-job
  ports:
    - protocol: TCP
      port: 7078
      targetPort: 7078